import { Memo } from '../states/memoState';
import { getDate } from './getDate';
import { getTime } from './getTime';
import { getNowDate } from './getNowDate';

const nowDate = getNowDate();
const date = getDate(nowDate);
const time = getTime(nowDate);

export const demoData: Memo[] = [
  {
    id: 1,
    body: 'ようこそ、チャットメモへ ^ ^',
    _text: ['ようこそ、チャットメモへ ^ ^'],
    completed: false,
    deleted: false,
    createdAt: nowDate,
    updatedAt: nowDate,
    completedAt: nowDate,
    deletedAt: nowDate,
    _date: date,
    _time: time,
    _synchronized: true,
    _tmpCompleted: false,
    _tmpCompletedAt: nowDate,
    _type: 'memo',
    _id: '1',
    comments: [],
  },
  {
    id: 2,
    body: '名前の通り、チャットのようなメモアプリです。',
    _text: ['名前の通り、チャットのようなメモアプリです。'],
    completed: false,
    deleted: false,
    createdAt: nowDate,
    updatedAt: nowDate,
    completedAt: nowDate,
    deletedAt: nowDate,
    _date: date,
    _time: time,
    _synchronized: true,
    _tmpCompleted: false,
    _tmpCompletedAt: nowDate,
    _type: 'memo',
    _id: '2',
    comments: [],
  },
  {
    id: 3,
    body: 'ぜひ一度使ってみてください！',
    _text: ['ぜひ一度使ってみてください！'],
    completed: false,
    deleted: false,
    createdAt: nowDate,
    updatedAt: nowDate,
    completedAt: nowDate,
    deletedAt: nowDate,
    _date: date,
    _time: time,
    _synchronized: true,
    _tmpCompleted: false,
    _tmpCompletedAt: nowDate,
    _type: 'memo',
    _id: '3',
    comments: [],
  },
  {
    id: 4,
    body: '※ ログインすると、メモが保存されるようになります。',
    _text: ['※ ログインすると、メモが保存されるようになります。'],
    completed: false,
    deleted: false,
    createdAt: nowDate,
    updatedAt: nowDate,
    completedAt: nowDate,
    deletedAt: nowDate,
    _date: date,
    _time: time,
    _synchronized: true,
    _tmpCompleted: false,
    _tmpCompletedAt: nowDate,
    _type: 'memo',
    _id: '4',
    comments: [],
  },
];
